---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  labels:
    kubernetes.io/service-name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
addressType: IPv4
endpoints:
- addresses:
    {{- range .Values.service.addresses }}
    - {{ . | title | quote }}
    {{- end }}
  conditions:
    ready: true
ports:
- name: {{ ternary "https" "http" .Values.secured }}
  port: {{ .Values.service.port }}
  protocol: TCP