{{- if .Values.addTLS }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.service.name }}
spec:
  hostnames:
  - {{ .Values.service.hostname }}}}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      namespace: {{ .Release.Namespace }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
{{- end }}