{{- if not .Values.addTLS }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: {{ .Values.service.name }}
spec:
  hostnames:
  - {{ .Values.service.hostname }}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      port: {{ .Values.service.port }}
      weight: 1
{{- end }}